# Project
kotlin.version=1.9.23
agp.version=8.2.2

# Android SDK
android.minSdk=24
android.compileSdk=34
android.targetSdk=34
android.ndkVersion=25.2.9519653


# Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options="-Xmx2048m"
org.gradle.caching=true
org.gradle.parallel=true
kotlin.code.style=official
android.useAndroidX=true
